[package]
name = "better_streams"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
pin-project-lite = "0.2.16"

[dev-dependencies]
tokio = { version = "1.47.1", features = ["full"] }
futures-executor = "0.3.31"
